### ISSUE TITLE
Type error when creating a new secret

### ISSUE THREAD

**Issue by gb1035** [digitalocean/netbox#1049]
### Issue type: Bug Report

**Python version: 2.7.9**
**NetBox version:2.0-beta2**

When adding a new secret I get a server error screen. I am using the superuser account currently.

Steps:
1. Selected a device
2. Add secret
3. Selected role
4. Enter secret
5. Submit
6. Received error screen

Below is the traceback from running in debug mode.
```
Performing system checks...

System check identified no issues (0 silenced).
April 06, 2017 - 01:41:36
Django version 1.11, using settings 'netbox.settings'
Starting development server at http://0.0.0.0:8002/
Quit the server with CONTROL-C.
Internal Server Error: /dcim/devices/9/add-secret/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/netbox-2.0-beta2/netbox/secrets/decorators.py", line 22, in wrapped_view
    return view(request, *args, **kwargs)
  File "/opt/netbox-2.0-beta2/netbox/secrets/views.py", line 83, in secret_add
    session_key = base64.b64decode(request.COOKIES.get('session_key', None))
  File "/usr/lib/python2.7/base64.py", line 73, in b64decode
    return binascii.a2b_base64(s)
TypeError: must be string or buffer, not None
[06/Apr/2017 01:41:47] "POST /dcim/devices/9/add-secret/ HTTP/1.1" 500 85437
```
Looking at my cookies for the site I do have a 'sessionid' cookie but not a 'session_key' cookie.

**Comment by jeremystretch** [comment]
The root cause here is that we attempt to base64-decode the session key even if it's `None`. The larger issue is that we don't prompt the user to acquire a session key before attempting to add/edit a secret.
