### ISSUE TITLE
KeyError: ('dcim', 'module') after upgrading to 2.0.3

### ISSUE THREAD

**Issue by matchaniat** [digitalocean/netbox#1216]
### Issue type: Error when migrate after upgrading to 2.0.3

**Python version:** 2.4
**NetBox version:** 2.0.3

After upgrading from 2.0.2 to 2.0.3, i have this issue when i try to migrate :
```shell
$ ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, tenancy, users
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/migrate.py", line 163, in handle
    pre_migrate_state = executor._create_project_state(with_applied_migrations=True)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/executor.py", line 81, in _create_project_state
    migration.mutate_state(state, preserve=False)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/migration.py", line 92, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/operations/fields.py", line 199, in state_forwards
    state.models[app_label, self.model_name_lower].fields
KeyError: ('dcim', 'module')
```

**Comment by jeremystretch** [comment]
GitHub issues are intended for reporting bugs and requesting features. For general discussion or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).
