### ISSUE TITLE
Gunicorn Supervisor/nginx Install Fails (V2.0.4)

### ISSUE THREAD

**Issue by thatdoodle** [digitalocean/netbox#1250]
### Issue type: Bug Report

**Python version: 3.5.2**
**NetBox version: 2.0.4**

   Followed the installation guide, and am getting stuck installing Gunicorn Supervisor & nginx on Ubuntu 16.04.2 LTS. Installation goes smoothly until I try to install these packages, at which point my terminal output looks like this;

```
/opt/netbox/netbox$ sudo apt-get install -y gunicorn supervisor
[sudo] password for administrator: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gunicorn is already the newest version (19.4.5-1ubuntu1).
supervisor is already the newest version (3.2.0-2ubuntu0.1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic linux-headers-4.4.0-70
  linux-headers-4.4.0-70-generic linux-headers-4.4.0-71
  linux-headers-4.4.0-71-generic linux-headers-4.4.0-72
  linux-headers-4.4.0-72-generic linux-headers-4.4.0-75
  linux-headers-4.4.0-75-generic linux-image-4.4.0-66-generic
  linux-image-4.4.0-70-generic linux-image-4.4.0-71-generic
  linux-image-4.4.0-72-generic linux-image-4.4.0-75-generic
  linux-image-extra-4.4.0-66-generic linux-image-extra-4.4.0-70-generic
  linux-image-extra-4.4.0-71-generic linux-image-extra-4.4.0-72-generic
  linux-image-extra-4.4.0-75-generic snap-confine ubuntu-core-launcher
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 2 not to upgrade.
7 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up python-setuptools (20.7.0-1) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-setuptools (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of python-gunicorn:
 python-gunicorn depends on python-setuptools; however:
  Package python-setuptools is not configured yet.

dpkg: error processing package python-gunicorn (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gunicorn:
 gunicorn depends on python-gunicorn (= 19.4.5-1ubuntu1); however:
  Package python-gunicorn is not configured yet.
 gunicorn depends on python-setuptools; however:
  Package python-setuptools is not configured yet.

dpkg: error processing package gunicorn (--configure):
 dependency problems - leaving unconfigured
Setting up python-pip (8.1.1-2ubuntu0.4) ...
No apport report written because the error message indicates it's a follow-up error from a previous failure.
                            No apport report written because the error message indicates it's a follow-up error from a previous failure.
                                                        Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-pip (--configure):
 subprocess installed post-installation script returned error exit status 1
No apport report written because MaxReports has already been reached
                                                                    Setting up python-wheel (0.29.0-1) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-wheel (--configure):
 subprocess installed post-installation script returned error exit status 1
Setting up python-meld3 (1.0.2-2) ...
No apport report written because MaxReports has already been reached
                                                                    Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-meld3 (--configure):
 subprocess installed post-installation script returned error exit status 1
No apport report written because MaxReports has already been reached
                                                                    dpkg: dependency problems prevent configuration of supervisor:
 supervisor depends on python-meld3; however:
  Package python-meld3 is not configured yet.

dpkg: error processing package supervisor (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports has already been reached
                                                                    Errors were encountered while processing:
 python-setuptools
 python-gunicorn
 gunicorn
 python-pip
 python-wheel
 python-meld3
 supervisor
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

This doesn't allow me to continue with the setup, as installing nginx gives the same error, resulting in the necessary files/directories not being created.

Output from nginx install;

```
/opt/netbox/netbox$ sudo apt-get install -y nginx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nginx is already the newest version (1.10.0-0ubuntu0.16.04.4).
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic linux-headers-4.4.0-70
  linux-headers-4.4.0-70-generic linux-headers-4.4.0-71
  linux-headers-4.4.0-71-generic linux-headers-4.4.0-72
  linux-headers-4.4.0-72-generic linux-headers-4.4.0-75
  linux-headers-4.4.0-75-generic linux-image-4.4.0-66-generic
  linux-image-4.4.0-70-generic linux-image-4.4.0-71-generic
  linux-image-4.4.0-72-generic linux-image-4.4.0-75-generic
  linux-image-extra-4.4.0-66-generic linux-image-extra-4.4.0-70-generic
  linux-image-extra-4.4.0-71-generic linux-image-extra-4.4.0-72-generic
  linux-image-extra-4.4.0-75-generic snap-confine ubuntu-core-launcher
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 2 not to upgrade.
7 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up python-setuptools (20.7.0-1) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-setuptools (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of python-gunicorn:
 python-gunicorn depends on python-setuptools; however:
  Package python-setuptools is not configured yet.

dpkg: error processing package python-gunicorn (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gunicorn:
 gunicorn depends on python-gunicorn (= 19.4.5-1ubuntu1); however:
  Package python-gunicorn is not configured yet.
 gunicorn depends on python-setuptools; however:
  Package python-setuptools is not configured yet.

dpkg: error processing package gunicorn (--configure):
 dependency problems - leaving unconfigured
Setting up python-pip (8.1.1-2ubuntu0.4) ...
No apport report written because the error message indicates it's a follow-up error from a previous failure.
                            No apport report written because the error message indicates it's a follow-up error from a previous failure.
                                                        Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-pip (--configure):
 subprocess installed post-installation script returned error exit status 1
No apport report written because MaxReports has already been reached
                                                                    Setting up python-wheel (0.29.0-1) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-wheel (--configure):
 subprocess installed post-installation script returned error exit status 1
No apport report written because MaxReports has already been reached
                                                                    Setting up python-meld3 (1.0.2-2) ...
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 35, in <module>
    from debpython.version import SUPPORTED, debsorted, vrepr, \
  File "/usr/share/python/debpython/version.py", line 24, in <module>
    from ConfigParser import SafeConfigParser
ImportError: No module named 'ConfigParser'
dpkg: error processing package python-meld3 (--configure):
 subprocess installed post-installation script returned error exit status 1
No apport report written because MaxReports has already been reached
                                                                    dpkg: dependency problems prevent configuration of supervisor:
 supervisor depends on python-meld3; however:
  Package python-meld3 is not configured yet.

dpkg: error processing package supervisor (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports has already been reached
                                                                    Errors were encountered while processing:
 python-setuptools
 python-gunicorn
 gunicorn
 python-pip
 python-wheel
 python-meld3
 supervisor
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Edit: Bad formatting - First bug report on Github
<!--

**Comment by jeremystretch** [comment]
Gunicorn, supervisor, and nginx are all independent application and are not part of NetBox. I'm not sure what has gone wrong with your installation, but you might consider seeking help on the [Ubuntu support forums](https://ubuntuforums.org/).
