### ISSUE TITLE
Migration fails if pycrypto is unistalled when upgrading from v2.2-beta2 to v2.2.1

### ISSUE THREAD

**Issue by afics** [digitalocean/netbox#1600]
### Issue type
[ ] Feature request 
[x] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.4.2
* NetBox version:  2.2.1

#### How to reproduce
Upgrading from ```v2.2-beta2``` to ```v2.2.1```.

Running the upgrade script does not remove the ```pycrypto``` library.
After verifying whether it is installed by running ```pip freeze | grep pycrypto```, I uninstalled it.

Now when running ```manage.py migrate```, the following error occurs:
```
Traceback (most recent call last):
  File "./netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/opt/netbox/venv/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/netbox/netbox/secrets/models.py", line 4, in <module>
    from Crypto.Cipher import AES, PKCS1_OAEP
```
#### Expected behaviour
The migration works fine without ```pycrypto```.

**Comment by afics** [comment]
As mentioned in #1578 reinstalling ```pycryptodome``` did the trick.
