### ISSUE TITLE
Server side error when creating device with custom_fields through the api

### ISSUE THREAD

**Issue by kicker69101** [digitalocean/netbox#1648]
### Issue type
[ ] Feature request 
[ X ] Bug report      
[ ] Documentation   

### Environment
* Python version:  2.7.5
* NetBox version:  2.1.5

### Description
I'm getting a server side exception when creating an object with custom_fields. Here is the exception:

`ERROR    Internal Server Error: /api/dcim/devices/#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner#012    response = get_response(request)#012  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response#012    response = self.process_exception_by_middleware(e, request)#012  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response#012    response = wrapped_callback(request, *callback_args, **callback_kwargs)#012  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view#012    return view_func(*args, **kwargs)#012  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 90, in view#012    return self.dispatch(request, *args, **kwargs)#012  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch#012    response = self.handle_exception(exc)#012  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception#012    self.raise_uncaught_exception(exc)#012  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch#012    response = handler(request, *args, **kwargs)#012  File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 20, in create#012    serializer.is_valid(raise_exception=True)#012  File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 237, in is_valid#012    self._validated_data = self.run_validation(self.initial_data)#012  File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 432, in run_validation#012    value = self.to_internal_value(data)#012  File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 462, in to_internal_value#012    validated_value = field.run_validation(primitive_value)#012  File "/usr/lib/python2.7/site-packages/rest_framework/fields.py", line 524, in run_validation#012    value = self.to_internal_value(data)#012  File "/opt/netbox/netbox/extras/api/customfields.py", line 30, in to_internal_value#012    for field_name, value in data.items():#012AttributeError: 'unicode' object has no attribute 'items'`

Here is the payload:

`{
"name":"***********",
"device_type":1772,
"device_role":31,
"tenant":null,
"platform":null,
"serial":"#########",
"asset_tag":null,
"site":16,
"rack":1133,
"position":25,
"face":0,
"status":1,
"primary_ip4":null,
"primary_ip6":null,
"comments":"",
"custom_fields":{"rack_tables_id":42}
}`

**Comment by 4ndersson** [comment]
I am getting almost the same when adding a device with custom_field.

Traceback:
```
Internal Server Error: /api/dcim/devices/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 431, in run_validation
    value = self.to_internal_value(data)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/serializers.py", line 461, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/fields.py", line 521, in run_validation
    value = self.to_internal_value(data)
  File "/opt/netbox/netbox/extras/api/customfields.py", line 30, in to_internal_value
    raise exception("asdasd")
AttributeError: 'str' object has no attribute 'items'
```

Payload:
```
	data = {
		"site": 7,
		"platform": 1,
		"device_role": 6 ,
		"tenant": 166,
		"device_type": 25,
		"name": 'test6',
		"status": 1,
		"custom_fields": {"service_id":123456},
	}
```

**Comment by RyanBreaker** [comment]
@kicker69101 When posting large blocks like you have, preface it with a line with ` ``` ` and end it with a line with ` ``` `. It'll then include the right formatting for lines and all for code and such and make it easier to read. 👍
See also: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by kicker69101** [comment]
@RyanBreaker Thanks, I'll will attempt to do this in future. However, in this case I pulled them from log files where they were already improperly formed.

**Comment by 4ndersson** [comment]
When the data is formed as `"custom_fields": {"service_id":123456}` ; It looks like  _/opt/netbox/netbox/extras/api/customfields.py_ only receives the string **service_id** but the loops in the script expects a dict.

I did a few changes in customfields.py and is now only sending in `"custom_fields : 123456`. Changes made in customfields.py (ugly, but it works for now):

line 30-40
```
        data_dict = {
        'service_id': ''
        }

        data_dict['service_id'] = data

for field_name, value in data_dict.items():
```

line 130-140
```
        field_dict = {
        "service_id" : ''
        }

        field_dict['service_id'] = custom_fields

        for field_name, value in field_dict.items():
```

**Comment by jeremystretch** [comment]
@kicker69101 Please upgrade to the latest version of NetBox (v2.2.2) and try again. If you still experience this issue, please amend your post to include complete instructions for reproducing the bug, beginning with the creation of a custom field.

**Comment by kicker69101** [comment]
The error remains after upgrade.

**Comment by kicker69101** [comment]
Steps to reproduce:

1. Create a custom field for devices named 'rack_tables_id' as an integer, but I get the same result as a string.
2. Using rest api create a device that has the following payload:
```{
"name":"***********",
"device_type":1772,
"device_role":31,
"tenant":null,
"platform":null,
"serial":"#########", 
"asset_tag":null, 
"site":16, 
"rack":1133, 
"position":25, 
"face":0, 
"status":1, 
"primary_ip4":null, 
"primary_ip6":null, 
"comments":"", 
"custom_fields":{
    "rack_tables_id":42
}
}```
3. I'm getting the following log entry (sorry for not formatting better, I'm getting this directly from a log file):```8502  139686073116480 django.request                                     ERROR    Internal Server Error: /api/dcim/devices/#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner#012    response = get_response(request)#012  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response#012    response = self.process_exception_by_middleware(e, request)#012  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response#012    response = wrapped_callback(request, *callback_args, **callback_kwargs)#012  File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view#012    return view_func(*args, **kwargs)#012  File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 90, in view#012    return self.dispatch(request, *args, **kwargs)#012  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch#012    response = self.handle_exception(exc)#012  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception#012    self.raise_uncaught_exception(exc)#012  File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch#012    response = handler(request, *args, **kwargs)#012  File "/usr/lib/python2.7/site-packages/rest_framework/mixins.py", line 20, in create#012    serializer.is_valid(raise_exception=True)#012  File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 236, in is_valid#012    self._validated_data = self.run_validation(self.initial_data)#012  File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 431, in run_validation#012    value = self.to_internal_value(data)#012  File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 461, in to_internal_value#012    validated_value = field.run_validation(primitive_value)#012  File "/usr/lib/python2.7/site-packages/rest_framework/fields.py", line 521, in run_validation#012    value = self.to_internal_value(data)#012  File "/opt/netbox/netbox/extras/api/customfields.py", line 30, in to_internal_value#012    for field_name, value in data.items():#012AttributeError: 'unicode' object has no attribute 'items'```

**Comment by jeremystretch** [comment]
@kicker69101 I'm not able to reproduce this. Please try sending the request manually using `curl` (see the docs for [examples](http://netbox.readthedocs.io/en/stable/api/examples/)) with the server running in debug mode and post the result.

**Comment by jeremystretch** [comment]
Closing due to lack of activity.
