### ISSUE TITLE
Migration dcim.0049_rackreservation_change_user is not applied due to IntegrityError: duplicate key value violates unique constraint "django_migrations_pkey"

### ISSUE THREAD

**Issue by Cosaquee** [digitalocean/netbox#1878]
### Issue type
[ ] Feature request
[X] Bug report
[ ] Documentation

### Environment
* Python version: 3.5.3
* NetBox version:  2.2.2 -> 2.2.9

### Description

I wanted to test version 2.2.9 before upgrading our production instance. Right now we are on version 2.2.2. I created fresh database and loaded our backup `psql netbox < netbox.sql`. Up to this point everything works, backup Is ok, data is in database. When I run migrations on downloaded Netbox 2.2.9 it show this error: 

```
Operations to perform:
  Apply all migrations: admin, auth, circuits, contenttypes, dcim, extras, ipam, secrets, sessions, tenancy, users, virtualization
Running migrations:
  Applying dcim.0049_rackreservation_change_user...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "django_migrations_pkey"
DETAIL:  Key (id)=(98) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 250, in apply_migration
    self.recorder.record_applied(migration.app_label, migration.name)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/recorder.py", line 73, in record_applied
    self.migration_qs.create(app=app, name=name)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "django_migrations_pkey"
DETAIL:  Key (id)=(98) already exists.
```

Current state of table django_migrations in our production database:
```
+----+--------+---------------------------+-------------------------------+
| id | app    | name                      | applied                       |
+----+--------+---------------------------+-------------------------------+
| 97 | extras | 0006_add_imageattachments | 2017-11-08 10:51:19.051385+00 |
+----+--------+---------------------------+-------------------------------+
| 98 | extras | 0007_unicode_literals | 2017-11-08 10:51:19.330987+00 |
+----+--------+-----------------------+-------------------------------+
| 99 | extras | 0008_reports | 2017-11-08 10:51:19.524447+00 |
+-----+------+---------------------+-------------------------------+
| 100 | ipam | 0019_virtualization | 2017-11-08 10:51:19.784064+00 |
+-----+------+---------------------+-------------------------------+
```

So we have exactly 110 rows in `django_migrations` table but somehow it want to add new migration with `(id)=(97)`. There was nothing custom done with database as far as I know.

I don't want to manually insert correct ID into migration, that will be pain to maintain. Any idea how to fix this problem?

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. GitHub issues are intended for reporting reproducible bugs and requesting features, and must be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). For general discussion, questions, or assistance with installation issues, please post to our [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss).

**Comment by Cosaquee** [comment]
@jeremystretch I don't get it, why you closed my issue if this is bug report that should be submitted here not on moiling list?
