### ISSUE TITLE
Drop-down Menu Failure

### ISSUE THREAD

**Issue by adunbrook** [digitalocean/netbox#2197]
### Issue type
[ ] Feature request 
[X] Bug report      
[ ] Documentation   

### Environment
* Python version:  3.5.2
* NetBox version:  2.3.4 

### Description
We noticed recently that when adding a new device the drop-down menus do not get populated with options. Example being the Manufacturer being selected but Device Type doesn't auto fill with options matching the Manufacturer. 

I went into the postgres and everything seems fine there with the ID values.

 This was occurring with version 2.3.2 and 2.3.4, so not an issue with the latest version. My only thought is that we updated something else on the server and it is causing an issue now.

**Comment by jeremystretch** [comment]
Thank you for your interest in NetBox. We require that all issues be submitted using the template provided [here](https://raw.githubusercontent.com/digitalocean/netbox/develop/.github/ISSUE_TEMPLATE.md). This is to ensure that only valid issues are reported and that each issue includes all the information necessary for a developer to act on it. Please update your issue so that it matches the template (this may require rewriting your issue entirely). This issue will be closed in one week if it has not been updated. Thanks!

**Comment by adunbrook** [comment]
Sorry for the late reply. 

I tested for API requests and see the GET request for the "add devices" page, but when I update the parent field I see nothing in the developer tools or an API request on the server.

```
192.168.0.42 - - [05/Jul/2018:08:55:35 -0400] "GET /dcim/devices/ HTTP/1.1" 200 38448 "https://fake.site/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
192.168.0.42 - - [05/Jul/2018:08:55:44 -0400] "GET /dcim/devices/add/ HTTP/1.1" 200 28602 "https://fake.site/dcim/devices/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
```

Also getting a weird jquery message in the debug:

```
jquery.min.js Failed to load resource: net::ERR_CONNECTION_REFUSED
jquery-3.3.1.min.js:2 jQuery.Deferred exception: $ is not a function TypeError: $ is not a function
    at HTMLDocument.<anonymous> (https://fake.site/static/js/forms.js?v2.3.4:4:5)
    at l (https://fake.site/static/js/jquery-3.3.1.min.js:2:29375)
    at c (https://fake.cite/static/js/jquery-3.3.1.min.js:2:29677) undefined
jquery-3.3.1.min.js:2 Uncaught TypeError: $ is not a function
    at HTMLDocument.<anonymous> (forms.js:4)
    at l (jquery-3.3.1.min.js:2)
    at c (jquery-3.3.1.min.js:2)
```
﻿

**Comment by jeremystretch** [comment]
Can't think of anything that would cause this. Try upgrading to v2.3.6, and be sure to re-run `python manage.py collectstatic`.

**Comment by jeremystretch** [comment]
Closing due to lack of activity.
