### ISSUE TITLE
500 From API when PUT with Empty Tags

### ISSUE THREAD

**Issue by zachmoody** [digitalocean/netbox#2294]
### Environment
* Python version:  2.7
* NetBox version:  2.4-dev

### Steps to Reproduce

Calling PUT on (at least) a Site object with no tags yields a 500.

### Observed Behavior
This is the traceback returned: 
traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/src/app/extras/middleware.py", line 82, in __call__
    obj.log_change(request.user, request.id, action)
  File "/usr/src/app/utilities/models.py", line 38, in log_change
    object_data=serialize_object(self)
  File "/usr/src/app/utilities/utils.py", line 105, in serialize_object
    data['tags'] = [tag.name for tag in obj.tags.all()]
AttributeError: 'list' object has no attribute 'all'
```
example payload:
```
{u'asn': 321,
 u'comments': u'',
 u'contact_email': u'',
 u'contact_name': u'',
 u'contact_phone': u'',
 u'count_circuits': 0,
 u'count_devices': 0,
 u'count_prefixes': 0,
 u'count_racks': 0,
 u'count_vlans': 0,
 u'created': u'2018-08-02',
 u'custom_fields': {},
 u'description': u'',
 u'facility': u'',
 u'id': 1,
 u'last_updated': u'2018-08-02T14:47:45.841002Z',
 u'latitude': None,
 u'longitude': None,
 u'name': u'TEST',
 u'physical_address': u'',
 u'region': None,
 u'shipping_address': u'',
 u'slug': u'test',
 u'status': 1,
 u'tags': [],
 u'tenant': None,
 u'time_zone': u'Africa/Abidjan'}
```

**Comment by jeremystretch** [comment]
Fixed in #2297
