### ISSUE TITLE
Cannot upgrade from 2.4.9 to 2.5.0 with python 3.4.2

### ISSUE THREAD

**Issue by anx-ag** [digitalocean/netbox#2713]
### Environment
* Python version:  3.4.2
* NetBox version:  2.4.9

### Steps to Reproduce
Run ./upgrade.sh for netbox 2.5.0

### Expected Behavior
A working upgrade to 2.5.0

### Observed Behavior
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "netbox/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 11, in <module>
    from django.conf import settings
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 18, in <module>
    from django.utils.functional import LazyObject, empty
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 12
    return _curried_func(*args, *moreargs, **{**kwargs, **morekwargs})
                                ^
SyntaxError: invalid syntax
Collecting static files (python3 netbox/manage.py collectstatic --no-input)...
Traceback (most recent call last):
  File "netbox/manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 11, in <module>
    from django.conf import settings
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 18, in <module>
    from django.utils.functional import LazyObject, empty
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 12
    return _curried_func(*args, *moreargs, **{**kwargs, **morekwargs})
                                ^
SyntaxError: invalid syntax

**Comment by jeremystretch** [comment]
NetBox v2.5 requires Django 2.1, which requires Python 3.5 or later.
