### ISSUE TITLE
ValueError after connecting a Power port to the feed on a PDU

### ISSUE THREAD

**Issue by phurrelmann** [digitalocean/netbox#3102]
### Environment
* Python version:  3.7.3
* NetBox version:  2.6-dev

### Steps to Reproduce
1. Create a device (PDU) with power outlets
2. Connect a device with its power ports to the PDU power outlets and define max. and allocated power on the device power ports
3. Create a power port on the PDU
4. On the PDU connect the Power Outlet to its Power port (input/leg)
5. Connect the PDU power port to a feed

### Expected Behavior

The PDU power port is connected to the feed and the power consumption is shown on the PDU.

### Observed Behavior

After connecting the input power port the following traceback is seen in log and the device (PDU) can no longer be shown/used. Everytime the following error is shown:

```python
<class 'ValueError'>

The annotation 'maximum_draw' conflicts with a field on the model.
```

Stacktrace in log:

```python
Internal Server Error: /dcim/devices/939/
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 85, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/dcim/views.py", line 987, in get
    'show_graphs': show_graphs,
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/defaulttags.py", line 161, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/opt/netbox/netbox/dcim/models.py", line 1945, in get_power_stats
    allocated_draw=Sum('allocated_draw'),
  File "/opt/netbox/venv/lib/python3.7/site-packages/cacheops/query.py", line 312, in aggregate
    qs = self.clone().annotate(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1052, in annotate
    "the model." % alias)
ValueError: The annotation 'maximum_draw' conflicts with a field on the model.
"GET /dcim/devices/939/ HTTP/1.1" 500 1782
```

**Comment by jeremystretch** [comment]
Please don't open bugs against the `develop-2.6` branch. It is still in active development.
