### ISSUE TITLE
2.6-development migration broken

### ISSUE THREAD

**Issue by erkib** [digitalocean/netbox#3173]
### Environment
* Python version:  3.6.7
* NetBox version:  2.6

### Steps to Reproduce
1. Run database migrations: $PYTHON manage.py migrate

### Expected Behavior
Database migrations completed successfully for version 2.6

### Observed Behavior
[apps@netbox-local netbox]$ /app/env/bin/python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/env/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/env/lib64/python3.6/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/app/env/lib64/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/app/env/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/app/env/lib64/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/app/env/lib64/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/app/env/lib64/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/app/env/lib64/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/app/env/lib64/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/app/env/lib64/python3.6/site-packages/django/urls/resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/app/env/lib64/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/app/env/lib64/python3.6/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/netbox/netbox/urls.py", line 7, in <module>
    from netbox.views import APIRootView, HomeView, SearchView
  File "/app/netbox/netbox/views.py", line 27, in <module>
    from ipam.tables import AggregateTable, IPAddressTable, PrefixTable, VLANTable, VRFTable
  File "/app/netbox/ipam/tables.py", line 5, in <module>
    from tenancy.tables import COL_TENANT, COL_TENANTGROUP_TENANT
ImportError: cannot import name 'COL_TENANTGROUP_TENANT'

**Comment by DanSheps** [comment]
It looks like you have somehow managed to merge in old history from develop to develop-2.6.

This line is not present in the current version of develop or develop-2.6.
