### ISSUE TITLE
CEST time zone is not recognized

### ISSUE THREAD

**Issue by jean-christophe-manciot** [digitalocean/netbox#341]
On ubuntu 16.04 
Netbox commit 46da9866e37867b5506c6b8450e938976c378e1f
All python requirements satisfied
```
./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 138, in __init__
    raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
ValueError: Incorrect timezone setting: CEST
```
**Workaround**: in configuration.py, changing TIME_ZONE = 'CEST' to TIME_ZONE = 'CET' removes the error.
CEST stands for "Central European Summer Time".

**Comment by cstueckrath** [comment]
this is expected. CEST is not a time zone. It is CET with DST and as such recognized (if you configure CET you will get CEST in the DST range)
