### ISSUE TITLE
unexpected keyword argument 'current_app'

### ISSUE THREAD

**Issue by rowco** [digitalocean/netbox#473]
Hi,

Installing for the first time - followed all instructions, but hitting this error. I can load the /admin page fine, but the / page triggers this error:

Traceback (most recent call last):
  File "/usr/lib64/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    response = self.get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = response_for_exception(request, exc)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 86, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 135, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/local/projects/netbox/netbox/netbox/views.py", line 62, in handle_500
    }, status=500)
  File "/usr/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 49, in render
    context_instance = RequestContext(request, current_app=current_app)
TypeError: __init__() got an unexpected keyword argument 'current_app'
`

**Comment by jeremystretch** [comment]
Please try re-installing NetBox. It seems that you've installed it in a location different from the location given in the docs. This should be fine, but make sure you replace all instance of `/opt/netbox` with `/usr/local/projects/netbox` in your case.

**Comment by rowco** [comment]
Hiya - thanks for the quick response. I've relocated the install to '/opt/netbox' and I'm getting the same exception.

**Comment by rowco** [comment]
I think I have the remnants of an old version of django on the system, a clear out and reinstall has got it all working. Thanks for your assistance.
