### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by cinsa** [digitalocean/netbox#649]
I'm having a problem when I want view or add an organization, rack, devices, etc. to my database. For example, when I choose from the top menu --> Organization  Sites and select a site, I get the following error:

![image](https://cloud.githubusercontent.com/assets/23103286/19774917/99375a6c-9c66-11e6-8328-5e4d5ae88bc6.png)

**Translate from spanish**: the "dcim_rackgroup.name" column should appear in the GROUP BY clause or be used in an aggregate function

Debug Output Web Browser:

![image](https://cloud.githubusercontent.com/assets/23103286/19775006/de78b7e2-9c66-11e6-8d82-4a0bbf2cd132.png)

Debug Output Shell:
`[27/Oct/2016 15:37:08] "GET /static/img/netbox.ico HTTP/1.1" 200 1174
Internal Server Error: /dcim/racks/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox-1.6.3/netbox/utilities/views.py", line 107, in get
    return render(request, self.template_name, context)
  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 94, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 323, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 323, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 1050, in render
    return render_value_in_context(output, context)
  File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 1028, in render_value_in_context
    value = force_text(value)
  File "/usr/local/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/usr/local/lib/python2.7/site-packages/django/utils/html.py", line 382, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "/usr/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 43, in __str__
    return self.as_widget()
  File "/usr/local/lib/python2.7/site-packages/django/forms/boundfield.py", line 101, in as_widget
    return force_text(widget.render(name, self.value(), attrs=attrs))
  File "/usr/local/lib/python2.7/site-packages/django/forms/widgets.py", line 600, in render
    options = self.render_options(value)
  File "/usr/local/lib/python2.7/site-packages/django/forms/widgets.py", line 550, in render_options
    for option_value, option_label in self.choices:
  File "/usr/local/lib/python2.7/site-packages/django/forms/models.py", line 1113, in __iter__
    for obj in queryset:
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: 
LINE 1: ...nteger)) AS "_dcim_site_name1", "dcim_site"."id", "dcim_site...
`

**Comment by jeremystretch** [comment]
It looks like you need to re-build the database as something went wrong during installation. If you continue to have issues, please post on the [mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) for assistance.
