### ISSUE TITLE
./manage.py error

### ISSUE THREAD

**Issue by CFRR** [digitalocean/netbox#699]
I'm trying install netbox following the documentation, and in section: Run Database Migrations, when I run the ./manage.py migrate I got the following error:

```
:/opt/netbox/netbox# ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/usr/lib/python2.6/site-packages/django/__init__.py", line 3, in <module>
    from django.utils.version import get_version
  File "/usr/lib/python2.6/site-packages/django/utils/version.py", line 7, in <module>
    from django.utils.lru_cache import lru_cache
  File "/usr/lib/python2.6/site-packages/django/utils/lru_cache.py", line 28
    fasttypes = {int, str, frozenset, type(None)},
                    ^
```

**Comment by jeremystretch** [comment]
GitHub issues are only for bug reports and feature requests. Please post to the [mailing list|https://groups.google.com/forum/#!forum/netbox-discuss] if you need assistance with installation. Thanks.
