### ISSUE TITLE
ImportError: No module named netbox.wsgi

### ISSUE THREAD

**Issue by coolool** [digitalocean/netbox#725]
So I keep getting this error. Any ideas to where netbox.wsgi is?

```root@Netbox: /opt/netbox/netbox/netbox# sudo gunicorn -c /opt/netbox/gunicorn_config.py netbox.wsgi
[2016-12-06 08:31:49 +0000] [4984] [INFO] Starting gunicorn 19.6.0
[2016-12-06 08:31:49 +0000] [4984] [INFO] Listening at: http://127.0.0.1:8001 (4984)
[2016-12-06 08:31:49 +0000] [4984] [INFO] Using worker: sync
[2016-12-06 08:31:49 +0000] [4989] [INFO] Booting worker with pid: 4989
[2016-12-06 08:31:49 +0000] [4989] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
ImportError: No module named netbox.wsgi
[2016-12-06 08:31:49 +0000] [4989] [INFO] Worker exiting (pid: 4989)
[2016-12-06 08:31:49 +0000] [4984] [INFO] Shutting down: Master
[2016-12-06 08:31:49 +0000] [4984] [INFO] Reason: Worker failed to boot.
```

**Comment by jeremystretch** [comment]
This looks like an installation issue; I'd suggest going through the web server portion of the [installation instructions](http://netbox.readthedocs.io/en/latest/installation/web-server/) again.

The GitHub issues should only be used for feature requests or bug reports. I'm going to close this issue, but please post to [the mailing list](https://groups.google.com/forum/#!forum/netbox-discuss) if you require further assistance.
