### ISSUE TITLE
./manage.py migrate Syntax error

### ISSUE THREAD

**Issue by wispsurgeon** [digitalocean/netbox#770]
Installing v1.8.0 on a fresh box on 14.04 gives the following error with v1.8.0

root@netbox:/opt/netbox/netbox# cd /opt/netbox/netbox/
root@netbox:/opt/netbox/netbox# ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/netbox-1.8.0/netbox/netbox/settings.py", line 9, in <module>
    import configuration
  File "/opt/netbox-1.8.0/netbox/netbox/configuration.py", line 14
    DATABASE = {
           ^
SyntaxError: invalid syntax

**Comment by jeremystretch** [comment]
Please see the [documentation](http://netbox.readthedocs.io/en/stable/configuration/mandatory-settings/) on configuring NetBox. You likely have an unclosed quote mark earlier in the configuration.
